sudo: required
services:
  - docker
before_install:
  - docker version && docker-compose version
  - gem install bundler
install:
  - make -j5 test-bundle
script:
  - make -j5 docker-compose
  - make test 2>make-test.err
after_failure:
  - "echo Tests failed, stderr was:"
  - cat make-test.err
