sudo: required
services:
  - docker
before_install:
  - echo BEFORE && docker version && docker-compose version
  - apt-cache madison docker-engine
  - sudo apt-get install -o Dpkg::Options::="--force-confnew" -y docker-engine=1.10.3-0~trusty
  - echo AFTER && docker version
  - gem install bundler
install:
  - make -j5 test-bundle
script:
  - make -j5 docker-compose
  - make test 2>make-test.err
after_failure:
  - "echo Tests failed, stderr was:"
  - cat make-test.err
